# Generated by Django 6.0 on 2025-12-04 23:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TiposExames",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("I", "Exame de imagem"), ("S", "Exame de sangue")],
                        max_length=1,
                    ),
                ),
                ("preco", models.FloatField()),
                ("disponivel", models.BooleanField(default=True)),
                ("horario_inicial", models.IntegerField()),
                ("horario_final", models.IntegerField()),
            ],
        ),
    ]
